### ISSUE TITLE
make bench fails with panic `more than two versions is not allowed`

### ISSUE THREAD

**Issue by aviadb** [elliotchance/vsql#74]
Running `make bench` fails after the SELECT stage of `bench-on-disk`

V full version: V 0.2.4 d4b3c65.d33f7d1
OS: Fedora linux

**Comment by elliotchance** [comment]
Thanks for raising this, the benchmark isn't part of CI and so was missed.

Assuming it's not actually a bug, this is caused by multiple transactions trying to manipulate the same record at the same time which would lead to conflicts when COMMIT comes around. Normally servers just lock until the new frozen record becomes available. However, that's a little trickier here as the transaction would have to relinquish control of the file and retry seamlessly (so the client sees it behave like a lock).

In any case this is a legitimate bug because the error I currently have is a lazy way to handle the situation so it needs to be improved regardless.
